# Generated by Django 2.2.4 on 2019-09-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainername', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='examdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=40)),
                ('answer2', models.CharField(max_length=40)),
                ('answer3', models.CharField(max_length=40)),
                ('answer4', models.CharField(max_length=40)),
                ('answer5', models.CharField(max_length=40)),
                ('cosmonaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.CosmoUser')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.CosmoTrainerdata')),
            ],
        ),
    ]
