# Generated by Django 2.2.4 on 2019-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20190902_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdata',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
