# Generated by Django 2.2.4 on 2019-09-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CosmoTrainerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=40)),
                ('authkey', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cosmotrainerdata',
            },
        ),
        migrations.CreateModel(
            name='CosmoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('passwd', models.CharField(max_length=40)),
                ('cwpasswd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cosmouser',
            },
        ),
    ]
